# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccdca6cfc308b381f54317a1490f7a4e27b68be66e1bb8d91f58802b30d2c051f8138e75d21992f498873801fbcf38e418b6171ee7ecda920fcce380ddc82612

test:
  secret_key_base: a5b794998d224b7e4951a50d6cafaaa48995bf5d6db1ed638649ebddd366ece861ea69c889c51db38a27a27fbb4eb2194dea34e093e9179118067c133ff59670

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
