# # # This file should contain all the record creation needed to seed the database with its default values.
# # # The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
# # #
# # # Examples:
# # #
# # #   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
# # #   Character.create(name: 'Luke', movie: movies.first)

# #  # Ingredient.create(name:"Red Tomatillo Salsa", price:1.00)
# #  # Ingredient.create(name:"Salsa Verde", price:1.00)
# #  # Ingredient.create(name:"Chipotle", price:1.00)
# #  # Ingredient.create(name:"Sourdough Bun", price:0.50)
# #  # Ingredient.create(name:"Classic Bun", price:0.50)
# #  # Ingredient.create(name:"Ketchup", price:0.25)
# #  # Ingredient.create(name:"Mustard", price:0.25)
# #  # Ingredient.create(name:"Mayo", price:0.25)
# #  # Ingredient.create(name:"Tomatoes", price:0.25)
# #  # Ingredient.create(name:"Onions", price:0.25)
# #  # Ingredient.create(name:"Avocado", price:1.25)
# #  # Ingredient.create(name:"Cilantro", price:0.75)
# #  # Ingredient.create(name:"Lettuce", price:0.25)
# #  # Ingredient.create(name:"E11ggs", price:0.75)
# #  # Ingredient.create(name:"Cheese", price:0.50)
# #  # Ingredient.create(name:"Beef Patty", price:1.00)
# #  # Ingredient.create(name:"Tater Tots", price:0.75)

# # # custom = BurgerType.create(name:"custom")
# # # original = BurgerType.create(name:"original")

# # # beverage = ItemType.create(name:"beverage")
# # # fries = ItemType.create(name:"fries")

# #  # french_fries = Item.create(name:"french_fries", item_type_id:2, price:1.50)
# #  # tater_totts = Item.create(name:"tater_totts", item_type_id:2, price:1.50)
# #  # banana_fries = Item.create(name:"banana_fries", item_type_id:2, price:1.50)
# #  # small_soda = Item.create(name:"small_soda", item_type_id:1, price:0.75)
# #  # large_soda = Item.create(name:"large_soda", item_type_id:1, price:1.25)
# #  # shake = Item.create(name:"shake", item_type_id:1, price:2.00)

# # # Jim = User.create(first_name:"James", last_name:"Lagattuta", email:"jim@gmail.com", admin:"true")
# # # OrderItem.create(user_id:1)
# classic_bun_cilantro_salsa_verde_burger = Burger.create(name:"classic_bun_cilantro_salsa_verde_burger", price:4.50, burger_type_id:2, order_item_id:1)
# # BurgerIngredient.create(burger_id:1, ingredient_id:4)
# # BurgerIngredient.create(burger_id:1, ingredient_id:7)
# # BurgerIngredient.create(burger_id:1, ingredient_id:6)
# # BurgerIngredient.create(burger_id:1, ingredient_id:5)
# # BurgerIngredient.create(burger_id:1, ingredient_id:1)
# # BurgerIngredient.create(burger_id:1, ingredient_id:8)
# # BurgerIngredient.create(burger_id:1, ingredient_id:15)
# # BurgerIngredient.create(burger_id:1, ingredient_id:12)
# # BurgerIngredient.create(burger_id:1, ingredient_id:11)
# # BurgerIngredient.create(burger_id:1, ingredient_id:13)

# avocado_on_grilled_sourdough_burger = Burger.create(name:"avocado_on_grilled_sourdough_burger", price:4.50, burger_type_id:2)
# # BurgerIngredient.create(burger_id:2, ingredient_id:3)
# # BurgerIngredient.create(burger_id:2, ingredient_id:2)
# # BurgerIngredient.create(burger_id:2, ingredient_id:5)
# # BurgerIngredient.create(burger_id:2, ingredient_id:1)
# # BurgerIngredient.create(burger_id:2, ingredient_id:8)
# # BurgerIngredient.create(burger_id:2, ingredient_id:15)
# # BurgerIngredient.create(burger_id:2, ingredient_id:12)
# # BurgerIngredient.create(burger_id:2, ingredient_id:11)

# chipotle_with_grilled_sourdough_burger = Burger.create(name:"chipotle_with_grilled_sourdough_burger", price:4.50, burger_type_id:2)

# # #BurgerIngredient.create(burger_id:3, ingredient_id:3)
# # #BurgerIngredient.create(burger_id:3, ingredient_id:5)
# # #BurgerIngredient.create(burger_id:3, ingredient_id:6)
# # #BurgerIngredient.create(burger_id:3, ingredient_id:1)
# # #BurgerIngredient.create(burger_id:3, ingredient_id:8)
# # #BurgerIngredient.create(burger_id:3, ingredient_id:15)
# # #BurgerIngredient.create(burger_id:3, ingredient_id:12)
# # #BurgerIngredient.create(burger_id:3, ingredient_id:11)
# # #BurgerIngredient.create(burger_id:3, ingredient_id:14)

# #fully_loaded_rabbits_burger = Burger.create(name:"fully_loaded_rabbits_burger", price:3.75, burger_type_id:2)

# # # BurgerIngredient.create(burger_id:4, ingredient_id:3)
# # # BurgerIngredient.create(burger_id:4, ingredient_id:11)
# # # BurgerIngredient.create(burger_id:4, ingredient_id:12)
# # # BurgerIngredient.create(burger_id:4, ingredient_id:5)
# # # BurgerIngredient.create(burger_id:4, ingredient_id:6)
# # # BurgerIngredient.create(burger_id:4, ingredient_id:1)
# # # BurgerIngredient.create(burger_id:4, ingredient_id:8)
# # # BurgerIngredient.create(burger_id:4, ingredient_id:15)

# salsa_verde_with_grilled_sourdough_burger = Burger.create(name:"Salsa Verde With Grilled Sourdough Burger", price:4.50, burger_type_id:2)

# # #BurgerIngredient.create(burger_id:5, ingredient_id:3)
# # #BurgerIngredient.create(burger_id:5, ingredient_id:5)
# # #BurgerIngredient.create(burger_id:5, ingredient_id:6)
# # #BurgerIngredient.create(burger_id:5, ingredient_id:1)
# # #BurgerIngredient.create(burger_id:5, ingredient_id:8)
# # #BurgerIngredient.create(burger_id:5, ingredient_id:15)
# # #BurgerIngredient.create(burger_id:5, ingredient_id:11)
# # #BurgerIngredient.create(burger_id:5, ingredient_id:12)
# # #BurgerIngredient.create(burger_id:5, ingredient_id:13)


# Breakfast_Burger = Burger.create(name:"Breakfast Burger", price:4.50, burger_type_id:2)

# # #BurgerIngredient.create(burger_id:6, ingredient_id:3)
# # #BurgerIngredient.create(burger_id:6, ingredient_id:12)
# # #BurgerIngredient.create(burger_id:6, ingredient_id:11)
# # #BurgerIngredient.create(burger_id:6, ingredient_id:1)
# # #BurgerIngredient.create(burger_id:6, ingredient_id:5)
# # #BurgerIngredient.create(burger_id:6, ingredient_id:9)
# # #BurgerIngredient.create(burger_id:6, ingredient_id:8)
# # #BurgerIngredient.create(burger_id:6, ingredient_id:7)
# # #BurgerIngredient.create(burger_id:6, ingredient_id:8)
# # #BurgerIngredient.create(burger_id:6, ingredient_id:15)
# # #BurgerIngredient.create(burger_id:6, ingredient_id:10)
# # #BurgerIngredient.create(burger_id:6, ingredient_id:2)
# # #BurgerIngredient.create(burger_id:6, ingredient_id:17)

# Burger.create(name:"Red Tomatillo Salsa Burger", price:4.50, burger_type_id:2)

# # # BurgerIngredient.create(burger_id:7, ingredient_id:3)
# # # BurgerIngredient.create(burger_id:7, ingredient_id:11)
# # # BurgerIngredient.create(burger_id:7, ingredient_id:12)
# # # BurgerIngredient.create(burger_id:7, ingredient_id:1)
# # # BurgerIngredient.create(burger_id:7, ingredient_id:6)
# # # BurgerIngredient.create(burger_id:7, ingredient_id:5)
# # # BurgerIngredient.create(burger_id:7, ingredient_id:8)
# # # BurgerIngredient.create(burger_id:7, ingredient_id:15)
# # # BurgerIngredient.create(burger_id:7, ingredient_id:17)

# Burger.create(name:"The Original on Classic Bun", price:3.70, burger_type_id:2)

# BurgerIngredient.create(burger_id:8, ingredient_id:4)
# BurgerIngredient.create(burger_id:8, ingredient_id:7)
# BurgerIngredient.create(burger_id:8, ingredient_id:6)
# BurgerIngredient.create(burger_id:8, ingredient_id:5)
# BurgerIngredient.create(burger_id:8, ingredient_id:1)
# BurgerIngredient.create(burger_id:8, ingredient_id:8)
# BurgerIngredient.create(burger_id:8, ingredient_id:15)
# BurgerIngredient.create(burger_id:8, ingredient_id:12)
# BurgerIngredient.create(burger_id:8, ingredient_id:11)

# BurgerIngredient.create(burger_id:1, ingredient_id:21)
# BurgerIngredient.create(burger_id:1, ingredient_id:23)
# BurgerIngredient.create(burger_id:1, ingredient_id:25)
# BurgerIngredient.create(burger_id:1, ingredient_id:26)
# BurgerIngredient.create(burger_id:1, ingredient_id:30)
# BurgerIngredient.create(burger_id:1, ingredient_id:32)
# BurgerIngredient.create(burger_id:1, ingredient_id:33)

# BurgerIngredient.create(burger_id:2, ingredient_id:22)
# BurgerIngredient.create(burger_id:2, ingredient_id:23)
# BurgerIngredient.create(burger_id:2, ingredient_id:25)
# BurgerIngredient.create(burger_id:2, ingredient_id:26)
# BurgerIngredient.create(burger_id:2, ingredient_id:30)
# BurgerIngredient.create(burger_id:2, ingredient_id:32)
# BurgerIngredient.create(burger_id:2, ingredient_id:33)

# BurgerIngredient.create(burger_id:3, ingredient_id:19)
# BurgerIngredient.create(burger_id:3, ingredient_id:21)
# BurgerIngredient.create(burger_id:3, ingredient_id:23)
# BurgerIngredient.create(burger_id:3, ingredient_id:25)
# BurgerIngredient.create(burger_id:3, ingredient_id:26)
# BurgerIngredient.create(burger_id:3, ingredient_id:30)
# BurgerIngredient.create(burger_id:3, ingredient_id:32)
# BurgerIngredient.create(burger_id:3, ingredient_id:33)

# BurgerIngredient.create(burger_id:4, ingredient_id:19)
# BurgerIngredient.create(burger_id:4, ingredient_id:22)
# BurgerIngredient.create(burger_id:4, ingredient_id:23)
# BurgerIngredient.create(burger_id:4, ingredient_id:25)
# BurgerIngredient.create(burger_id:4, ingredient_id:26)
# BurgerIngredient.create(burger_id:4, ingredient_id:27)
# BurgerIngredient.create(burger_id:4, ingredient_id:29)
# BurgerIngredient.create(burger_id:4, ingredient_id:30)
# BurgerIngredient.create(burger_id:4, ingredient_id:32)
# BurgerIngredient.create(burger_id:4, ingredient_id:33)



# BurgerIngredient.create(burger_id:5, ingredient_id:20)
# BurgerIngredient.create(burger_id:5, ingredient_id:21)
# BurgerIngredient.create(burger_id:5, ingredient_id:23)
# BurgerIngredient.create(burger_id:5, ingredient_id:25)
# BurgerIngredient.create(burger_id:5, ingredient_id:26)
# BurgerIngredient.create(burger_id:5, ingredient_id:30)
# BurgerIngredient.create(burger_id:5, ingredient_id:32)
# BurgerIngredient.create(burger_id:5, ingredient_id:33)


# BurgerIngredient.create(burger_id:6, ingredient_id:18)
# BurgerIngredient.create(burger_id:6, ingredient_id:21)
# BurgerIngredient.create(burger_id:6, ingredient_id:23)
# BurgerIngredient.create(burger_id:6, ingredient_id:25)
# BurgerIngredient.create(burger_id:6, ingredient_id:26)
# BurgerIngredient.create(burger_id:6, ingredient_id:27)
# BurgerIngredient.create(burger_id:6, ingredient_id:30)
# BurgerIngredient.create(burger_id:6, ingredient_id:32)
# BurgerIngredient.create(burger_id:6, ingredient_id:33)


# BurgerIngredient.create(burger_id:7, ingredient_id:21)
# BurgerIngredient.create(burger_id:7, ingredient_id:28)
# BurgerIngredient.create(burger_id:7, ingredient_id:23)
# BurgerIngredient.create(burger_id:7, ingredient_id:25)
# BurgerIngredient.create(burger_id:7, ingredient_id:26)
# BurgerIngredient.create(burger_id:7, ingredient_id:30)
# BurgerIngredient.create(burger_id:7, ingredient_id:32)
# BurgerIngredient.create(burger_id:7, ingredient_id:33)

#  BurgerIngredient.create(burger_id:8, ingredient_id:21)
#  BurgerIngredient.create(burger_id:8, ingredient_id:23)
#  BurgerIngredient.create(burger_id:8, ingredient_id:25)
#  BurgerIngredient.create(burger_id:8, ingredient_id:26)
#  BurgerIngredient.create(burger_id:8, ingredient_id:29)
#  BurgerIngredient.create(burger_id:8, ingredient_id:30)
#  BurgerIngredient.create(burger_id:8, ingredient_id:31)
#  BurgerIngredient.create(burger_id:8, ingredient_id:32)
#  BurgerIngredient.create(burger_id:8, ingredient_id:33)
#  BurgerIngredient.create(burger_id:8, ingredient_id:34)